name: Prettier on Pull Request to dev

on:
  pull_request:
    branches:
      - dev

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Check prettier binary
        run: |
          ls -l ./node_modules/.bin/prettier
          file ./node_modules/.bin/prettier || true
          head -n 1 ./node_modules/.bin/prettier || true

      - name: Run Prettier
        run: npx prettier --write .
